const posts = [
  {
    id: 1,
    username: "alex.wanderer",
    avatar: "https://i.pravatar.cc/100?img=1",
    image: "https://picsum.photos/600/600?random=1",
    likes: 3241,
    caption: "Lost in the mountains, found myself. 🏔️",
    time: "2h",
  },
  {
    id: 2,
    username: "sara.lens",
    avatar: "https://i.pravatar.cc/100?img=5",
    image: "https://picsum.photos/600/600?random=2",
    likes: 8870,
    caption: "Golden hour never disappoints. 🌅",
    time: "4h",
  },
  {
    id: 3,
    username: "mike.travels",
    avatar: "https://i.pravatar.cc/100?img=12",
    image: "https://picsum.photos/600/600?random=3",
    likes: 1504,
    caption: "Every city has its own heartbeat. 🏙️",
    time: "6h",
  },
  {
    id: 4,
    username: "priya.create",
    avatar: "https://i.pravatar.cc/100?img=20",
    image: "https://picsum.photos/600/600?random=4",
    likes: 5610,
    caption: "Art is not what you see, but what you make others see. 🎨",
    time: "8h",
  },
  {
    id: 5,
    username: "james.fit",
    avatar: "https://i.pravatar.cc/100?img=33",
    image: "https://picsum.photos/600/600?random=5",
    likes: 2103,
    caption: "Morning grind never stops. 💪",
    time: "10h",
  },
  {
    id: 6,
    username: "luna.vibes",
    avatar: "https://i.pravatar.cc/100?img=47",
    image: "https://picsum.photos/600/600?random=6",
    likes: 9320,
    caption: "Chasing sunsets and good vibes only. 🌊",
    time: "12h",
  },
  {
    id: 7,
    username: "dan.shoots",
    avatar: "https://i.pravatar.cc/100?img=60",
    image: "https://picsum.photos/600/600?random=7",
    likes: 4788,
    caption: "One click, a thousand words. 📷",
    time: "14h",
  },
  {
    id: 8,
    username: "nour.daily",
    avatar: "https://i.pravatar.cc/100?img=9",
    image: "https://picsum.photos/600/600?random=8",
    likes: 6230,
    caption: "Simple moments, big memories. ✨",
    time: "16h",
  },
  {
    id: 9,
    username: "leo.explore",
    avatar: "https://i.pravatar.cc/100?img=52",
    image: "https://picsum.photos/600/600?random=9",
    likes: 3870,
    caption: "Not all those who wander are lost. 🌿",
    time: "18h",
  },
  {
    id: 10,
    username: "zoe.studio",
    avatar: "https://i.pravatar.cc/100?img=44",
    image: "https://picsum.photos/600/600?random=10",
    likes: 7145,
    caption: "Creating something from nothing every single day. 🎬",
    time: "20h",
  },
  {
    id: 11,
    username: "ravi.clicks",
    avatar: "https://i.pravatar.cc/100?img=17",
    image: "https://picsum.photos/600/600?random=11",
    likes: 1985,
    caption: "Colors speak louder than words. 🌈",
    time: "22h",
  },
  {
    id: 12,
    username: "maya.world",
    avatar: "https://i.pravatar.cc/100?img=29",
    image: "https://picsum.photos/600/600?random=12",
    likes: 11240,
    caption: "The world is a book, and those who don't travel read only one page. 📖",
    time: "1d",
  },
];

export default posts;
